title: Rucha Pendharkar
author: Rucha Pendharkar
remote_theme: jekyll/minima

minima:
  skin: dark

plugins:
  - jekyll-feed
  - jekyll-seo-tag

social_links:
    - { platform: github, user_url: "https://github.com/ruchapendharkar" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/ruchapendharkar" }
header_pages:
    - blog.md
