title: Rucha Pendharkar
description: Rucha's Website
author: Rucha Pendharkar
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

minima:
  skin: dark
  social_links:
    - { platform: github, user_url: "https://github.com/ruchapendharkar" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/ruchapendharkar" }
  header_pages:
    - blog.md
