# Site Build Settings

paginate: 5
paginate_path: "/blog/page:num"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

# Site Info
title: "Rucha Pendharkar"
description: "Almost always a work in progress"
author: "Rucha Pendharkar"

# Navigation (used in _data/settings.yml if Lagrange is configured that way)
navigation:
  - title: "Scribbles"
    url: "/blog/"
  - title: "Timeline"
    url: "/timeline/"

# Feed configuration (optional)
# feed:
#   path: rss-feed.xml
